Lab 02 : 자료형(2) & if문
- 목차
    1. 자료형 - 숫자형, 문자열, **튜플, 딕셔너리, 집합, 불, 변수**

지금까지 우리는 숫자와 문자열에 대해서 알아보았다. 하지만 숫자와 문자열만으로 프로그래밍을 하기엔 부족한 점이 많다. 예를 들어 1부터 10까지의 숫자 중 홀수 모음인 1, 3, 5, 7, 9의 집합을 생각해 보자. 이런 숫자 모음을 숫자나 문자열로 표현하기는 쉽지 않다. 파이썬에는 이러한 불편함을 해소할 수 있는 자료형이 존재한다. 그것이 바로 여기에서 공부할 리스트(List)이다.

# 리스트 자료형

1. 리스트는 어떻게 만들고 사용할까?
2. 리스트의 인덱싱과 슬라이싱
   1. 리스트의 인덱싱
   2. 리스트의 슬라이싱
3. 리스트 연산하기
   1. 리스트 더하기(+)
   2. 리스트 반복하기(*)
   3. 리스트 길이구하기
4. 리스트의 수정과 삭제
   1. 리스트에서 값 수정하기
   2. del 함수 사용해 리스트 요소 삭제하기
5. 리스트 관련 함수들
   1. 리스트에 요소 추가(`append`)
   2. 리스트 정렬(`sort`)
   3. 리스트 뒤집기(`reverse`)
   4. 위치 반환(`index`)
   5. 리스트에 요소 삽입(`insert`)
   6. 리스트 요소 제거(`remove`)
   7. 리스트 요소 끄집어내기(`pop`)
   8. 리스트에 포함된 요소 x의 개수 세기(`count`)
   9. 리스트 확장(`extend`)

## 리스트는 어떻게 만들고 사용할까?
리스트를 사용하면 1, 3, 5, 7, 9 숫자 모음을 다음과 같이 간단하게 표현할 수 있다.

In [41]:
odd = [1, 3, 5, 7, 9]
odd

[1, 3, 5, 7, 9]

리스트를 만들 때는 위에서 보는 것과 같이 대괄호(`[ ]`)로 감싸 주고 각 요솟값은 쉼표(`,`)로 구분해 준다.  
`리스트명 = [요소1, 요소2, 요소3, ...]`

In [42]:
a = []
b = [1, 2, 3]
c = ['Life', 'is', 'too', 'short']
d = [1, 2, 'Life', 'is']
e = [1, 2, ['Life', 'is']]

In [40]:
# 빈 리스트 생성
a = list()
a = []

In [41]:
"""
Quiz1. 리스트 생성
영화 : 닥터 스트레인지, 스플릿, 럭키
빈 리스트를 movie_rank의 이름으로 만들어준 후, 영화 제목들을 리스트에 저장하시오.
"""

movie_rank = []
movie_rank = ["닥터 스트레인지", "스플릿", "럭키"]
movie_rank

['닥터 스트레인지', '스플릿', '럭키']

## 리스트의 인덱싱과 슬라이싱
리스트도 문자열처럼 인덱싱과 슬라이싱이 가능하다. 백문이 불여일견. 말로 설명하는 것보다 직접 예를 실행해 보면서 리스트의 기본 구조를 이해하는 것이 쉽다. 대화형 인터프리터로 따라 하며 확실하게 이해하자.

### 리스트의 인덱싱
리스트 역시 문자열처럼 인덱싱을 적용할 수 있다. 먼저 `a` 변수에 `[1, 2, 3]` 값을 설정한다.

In [43]:
a = [1, 2, 3]
a
[1, 2, 3]

[1, 2, 3]

`a[0]`은 리스트 `a`의 첫 번째 요솟값을 말한다.

In [44]:
# 인덱싱 기법으로 리스트 a의 요솟값 찾기
a[0]

1

In [45]:
# 인덱싱 기법으로 리스트 a의 요솟값끼리 사칙연산하기
a[0] + a[2]

4

In [19]:
# -1은 마지막 값을 출력한다
a[-1]

3

이번에는 다음 예처럼 리스트 `a`를 숫자` 1, 2, 3`과 또 다른 리스트인 `['a', 'b', 'c']`를 포함하도록 만들어 보자.

In [21]:
a = [1, 2, 3, ['a', 'b', 'c']]
a

[1, 2, 3, ['a', 'b', 'c']]

In [24]:
a[0]

1

In [25]:
a[-1]

['a', 'b', 'c']

In [26]:
a[3]

['a', 'b', 'c']

예상한 대로 `a[-1]`은 마지막 요솟값 `['a', 'b', 'c']`를 나타낸다. `a[3]`은 리스트 `a`의 네 번째 요소를 나타내기 때문에 마지막 요소를 나타내는 `a[-1]`과 동일한 결괏값을 보여 준다.

그렇다면 여기에서 리스트 `a`에 포함된 `['a', 'b', 'c']` 리스트에서 `'a' `값을 인덱싱을 사용해 끄집어낼 수 있는 방법은 없을까? 다음 예를 보자.

In [27]:
a[-1][0]

'a'

위와 같이 하면 'a'를 끄집어낼 수 있다. a[-1]이 ['a', 'b', 'c'] 리스트라는 것은 이미 말했다. 바로 이 리스트에서 첫 번째 요소를 불러오기 위해 [0]을 붙여 준 것이다.

다음 예도 마찬가지 경우이므로 어렵지 않게 이해될 것이다.

In [28]:
a[-1][1]

'b'

In [29]:
a[-1][2]

'c'

In [ ]:
'''
Quiz2. movie_rank의 마지막 요소를 구하여라
'''
movie_rank[-1]

### 리스트의 슬라이싱
문자열과 마찬가지로 리스트에서도 슬라이싱 기법을 적용할 수 있다. 슬라이싱은 ‘나눈다’는 뜻이라고 했다.



In [34]:
# 리스트의 슬라이싱
a = [1, 2, 3, 4, 5]
a[0:2]

[1, 2]

In [35]:
# 문자열의 슬라이싱
a = "12345"
a[0:2]

'12'

2가지가 완전히 동일하게 사용되었음을 눈치챘을 것이다. 문자열에서 했던 것과 사용법이 완전히 동일하다.



In [36]:
a = [1, 2, 3, 4, 5]
b = a[:2]
c = a[2:]

In [38]:
b

[1, 2]

In [39]:
c

[3, 4, 5]

`b` 변수는 리스트 `a`의 첫 번째 요소부터 두 번째 요소인 `a[1]`까지 나타내는 리스트이다. 물론 `a[2]` 값인 3은 포함되지 않는다. `c`라는 변수는 리스트 `a`의 세 번째 요소부터 끝까지 나타내는 리스트이다.

## 리스트 연산하기
리스트 역시 `+` 기호를 사용해서 더할 수 있고 `*` 기호를 사용해서 반복할 수 있다. 문자열과 마찬가지로 리스트에서도 되는지 직접 확인해 보자.

#### 리스트 더하기(+)

In [47]:
a = [1, 2, 3]
b = [4, 5, 6]
a + b

[1, 2, 3, 4, 5, 6]

리스트 사이에서 `+` 기호는 2개의 리스트를 합치는 기능을 한다. 문자열에서 `"abc" + "def" = "abcdef"`가 되는 것과 같은 이치이다.

#### 리스트 반복하기(`*`)

In [48]:
a = [1, 2, 3]
a * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

위에서 볼 수 있듯이 `[1, 2, 3]` 리스트가 세 번 반복되어 새로운 리스트를 만들어낸다. 문자열에서 `"abc" * 3 = "abcabcabc"` 가 되는 것과 같은 이치이다

#### 리스트 길이 구하기(`len`)

In [49]:
a = [1, 2, 3]
len(a)

3

`len` 함수는 문자열, 리스트 외에 앞으로 배울 튜플과 딕셔너리에도 사용할 수 있는 함수이다. 실습에서 자주 사용하니 잘 기억해 두자.
## 리스트의 수정과 삭제
#### 리스트에서 값 수정하기

In [2]:
a = [1, 2, 3]
a[2] = 4
a # a[2]의 요솟값 3이 4로 바뀌었다.

[1, 2, 4]

#### `del` 함수를 사용해 리스트 요소 삭제하기

In [3]:
a = [1, 2, 3]
del a[1]
a

[1, 3]

`del a[x]`는 `x`번째 요솟값을 삭제한다. 여기에서는 `a` 리스트에서 `a[1]`을 삭제하는 방법을 보여준다. `del` 함수는 파이썬이 자체적으로 가지고 있는 삭제 함수이며 다음과 같이 사용한다.

In [4]:
a = [1, 2, 3, 4, 5]
del a[2:]
a

[1, 2]

`a[2:]`에 해당하는 리스트의 요소들이 삭제되었다.

리스트의 요소를 삭제하는 방법에는 2가지가 더 있다. 그것은 리스트의 `remove와` `pop` 함수를 사용하는 방법인데 이것에 대해서는 바로 이어지는 리스트 관련 함수에서 설명한다.



## 리스트 관련 함수들

문자열과 마찬가지로 리스트 변수 이름 뒤에 `'.'`를 붙여서 여러 가지 리스트 관련 함수를 사용할 수 있다. 유용하게 사용되는 리스트 관련 함수 몇 가지에 대해서만 알아보기로 하자.

#### 리스트에 요소 추가(`append`)


In [7]:
a = [1, 2, 3]
a.append(4)
a

[1, 2, 3, 4]

In [8]:
a.append([5,6])
a

[1, 2, 3, 4, [5, 6]]

In [9]:
a = [1, 4, 3, 2]
a.sort()
a

[1, 2, 3, 4]

In [10]:
a = ['a', 'c', 'b']
a.sort()
a

['a', 'b', 'c']

In [43]:
'''
Quiz3. movie_rank 리스트에 "배트맨"을 추가하여라.
'''
movie_rank.append("배트맨")
print(movie_rank)

['닥터 스트레인지', '스플릿', '럭키', '배트맨']


#### 리스트 뒤집기(`reverse`)


In [11]:
a = ['a', 'c', 'b']
a.reverse()
a

['b', 'c', 'a']

#### 위치 반환(`index`)
`index(x)` 함수는 리스트에 `x` 값이 있으면 `x`의 위치 값을 돌려준다.



In [12]:
a = [1,2,3]
a.index(3)

2

In [13]:
a.index(1)

0

In [14]:
a.index(0)

ValueError: 0 is not in list

#### 리스트에 요소 삽입(`insert`)
`insert(a, b)`는 리스트의 `a`번째 위치에 `b`를 삽입하는 함수이다. 파이썬에서는 숫자를 0부터 센다는 것을 반드시 기억하자.

In [15]:
a = [1, 2, 3]
a.insert(0, 4)
a

[4, 1, 2, 3]

In [16]:
a.insert(3, 5)
a

[4, 1, 2, 5, 3]

In [45]:
'''
Quiz4. movie_rank 리스트에서 "슈퍼맨"을 "닥터 스트레인지"와 "스플릿" 사이에 추가하라.
'''
movie_rank.insert(1, "슈퍼맨")
movie_rank

['닥터 스트레인지', '슈퍼맨', '스플릿', '럭키', '배트맨']

#### 리스트 요소 제거(`remove`)
`remove(x)`는 리스트에서 첫 번째로 나오는 `x`를 삭제하는 함수이다.



In [18]:
a = [1, 2, 3, 1, 2, 3]
a.remove(3)
a

[1, 2, 1, 2, 3]

In [46]:
'''
Quiz5. movie_rank 리스트에서 '럭키'를 삭제하라.
'''
print(movie_rank)
del movie_rank[3]
print(movie_rank)

['닥터 스트레인지', '슈퍼맨', '스플릿', '럭키', '배트맨']
['닥터 스트레인지', '슈퍼맨', '스플릿', '배트맨']


In [49]:
'''
Quiz5. movie_rank 리스트에서 '스플릿' 과 '배트맨'을 를 삭제하라.
'''
movie_rank = ['닥터 스트레인지', '슈퍼맨', '스플릿', '배트맨']
print(movie_rank)
del movie_rank[2]
del movie_rank[2]
print(movie_rank)

['닥터 스트레인지', '슈퍼맨', '스플릿', '배트맨']
['닥터 스트레인지', '슈퍼맨']


In [50]:
'''
Quiz5. movie_rank 리스트에서 '스플릿' 과 '배트맨'을 를 삭제하라.
'''
movie_rank = ['닥터 스트레인지', '슈퍼맨', '스플릿', '배트맨']
print(movie_rank)
del movie_rank[2:4]
print(movie_rank)

['닥터 스트레인지', '슈퍼맨', '스플릿', '배트맨']
['닥터 스트레인지', '슈퍼맨']


#### 리스트 요소 끄집어내기(`pop`)
`pop()`은 리스트의 맨 마지막 요소를 돌려주고 그 요소는 삭제한다.



In [25]:
a = [1,2,3]
print(a.pop(), a)

3 [1, 2]


#### 리스트에 포함된 요소 x의 개수 세기(`count`)
`count(x)`는 리스트 안에 x가 몇 개 있는지 조사하여 그 개수를 돌려주는 함수이다.

In [26]:
a = [1,2,3,1]
a.count(1)

2

#### 리스트 확장(`extend`)
`extend(x)`에서 `x`에는 리스트만 올 수 있으며 원래의 `a` 리스트에 `x` 리스트를 더하게 된다.

In [36]:
a = [1,2,3]
a.extend([4,5])
a

[1, 2, 3, 4, 5]

In [37]:
a = [1,2,3]
a += [4, 5]
a

[1, 2, 3, 4, 5]

In [32]:
b = [6, 7]
a.extend(b)
a

[1, 2, 3, 4, 5, 6, 7]

In [51]:
'''
Quiz6. 회사 이름이 슬래시 ('/')로 구분되어 하나의 문자열로 저장되어 있다.
이를 company_list 이름의 리스트로 분리 저장하라.
'''

company = "삼성전자/LG전자/Naver"
company_list = company.split("/")
print(company_list)

['삼성전자', 'LG전자', 'Naver']


# 튜플 자료형
1. 튜플은 어떻게 만들까?
2. 튜플의 요소값을 지우거나 변경하려고 하면 어떻게 될까?
3. 튜플 다루기
   1. 인덱싱하기
   2. 슬라이싱하기
   3. 튜플 더하기
   4. 튜플 곱하기
   5. 길이 구하기

## 튜플은 어떻게 만들까?
튜플(tuple)은 몇 가지 점을 제외하곤 리스트와 거의 비슷하며 리스트와 다른 점은 다음과 같다.  

리스트는 [ ]으로 둘러싸지만 튜플은 ( )으로 둘러싼다.  
리스트는 그 값의 생성, 삭제, 수정이 가능하지만 튜플은 그 값을 바꿀 수 없다.  
튜플의 모습은 다음과 같다.

In [52]:
t1 = ()
t2 = (1,)
t3 = (1, 2, 3)
t4 = 1, 2, 3
t5 = ('a', 'b', ('ab', 'cd'))

리스트와 모습은 거의 비슷하지만 튜플에서는 리스트와 다른 2가지 차이점을 찾아볼 수 있다.   
t2 = (1,)처럼 단지 1개의 요소만을 가질 때는 요소 뒤에 콤마(,)를 반드시 붙여야 한다는 것과 t4 = 1, 2, 3처럼 괄호( )를 생략해도 무방하다는 점이다.  

얼핏 보면 튜플과 리스트는 비슷한 역할을 하지만 프로그래밍을 할 때 튜플과 리스트는 구별해서 사용하는 것이 유리하다. 튜플과 리스트의 가장 큰 차이는 값을 변화시킬 수 있는가 여부이다. 즉 리스트의 항목 값은 변화가 가능하고 튜플의 항목 값은 변화가 불가능하다. 따라서 프로그램이 실행되는 동안 그 값이 항상 변하지 않기를 바란다거나 값이 바뀔까 걱정하고 싶지 않다면 주저하지 말고 튜플을 사용해야 한다. 이와는 반대로 수시로 그 값을 변화시켜야할 경우라면 리스트를 사용해야 한다. 실제 프로그램에서는 값이 변경되는 형태의 변수가 훨씬 많기 때문에 평균적으로 튜플보다는 리스트를 더 많이 사용한다.

## 튜플의 요소값을 지우거나 변경하려고 하면 어떻게 될까?
-> 에러가 뜬다

튜플은 값을 변화시킬 수 없다는 점만 제외하면 리스트와 완전히 동일하므로 간단하게만 살펴보겠다. 다음 예제는 서로 연관되어 있으므로 차례대로 수행해 보기 바란다.


In [53]:
# 인덱싱
t1 = (1, 2, 'a', 'b')
t1[0]

'b'

In [54]:
t1[3]

'b'

In [55]:
# 슬라이싱
t1 = (1, 2, 'a', 'b')
t1[1:]

(2, 'a', 'b')

In [56]:
# 사칙연산, 길이 구하기
t1 = (1, 2, 'a', 'b')
t2 = (3, 4)
t1 + t2

(1, 2, 'a', 'b', 3, 4)

In [57]:
len(t1)

4

# 딕셔너리 자료형
1. 딕셔너리란?
2. 딕셔너리는 어떻게 만들까?
3. 딕셔너리 쌍 추가, 삭제하기
   1. 딕셔너리 쌍 추가하기
   2. 딕셔너리 요소 삭제하기
4. 딕셔너리를 사용하는 방법
   1. 딕셔너리에서 Key 사용해 Value 얻기
   2. 딕셔너리 만들 때 주의할 사항
5. 딕셔너리 관련 함수들
   1. Key 리스트 만들기(`keys`)
   2. Value 리스트 만들기(`values`)
   3. Key, Value 쌍 얻기(`items`)
   4. Key: Value 쌍 모두 지우기(`clear`)
   5. Key로 Value얻기(`get`)
   6. 해당 Key가 딕셔너리 안에 있는지 조사하기(`in`)

### 1. 딕셔너리란?
사람은 누구든지 "이름" = "홍길동", "생일" = "몇 월 며칠" 등으로 구별할 수 있다. 파이썬은 영리하게도 이러한 대응 관계를 나타낼 수 있는 자료형을 가지고 있다. 요즘 사용하는 대부분의 언어도 이러한 대응 관계를 나타내는 자료형을 갖고 있는데, 이를 연관 배열(Associative array) 또는 해시(Hash)라고 한다.

파이썬에서는 이러한 자료형을 딕셔너리(Dictionary)라고 하는데, 단어 그대로 해석하면 사전이라는 뜻이다. 즉 "people"이라는 단어에 "사람", "baseball"이라는 단어에 "야구"라는 뜻이 부합되듯이 딕셔너리는 Key와 Value를 한 쌍으로 갖는 자료형이다. 예컨대 Key가 "baseball"이라면 Value는 "야구"가 될 것이다.

딕셔너리는 리스트나 튜플처럼 순차적으로(sequential) 해당 요솟값을 구하지 않고 Key를 통해 Value를 얻는다. 이것이 바로 딕셔너리의 가장 큰 특징이다. baseball이라는 단어의 뜻을 찾기 위해 사전의 내용을 순차적으로 모두 검색하는 것이 아니라 baseball이라는 단어가 있는 곳만 펼쳐 보는 것이다.

### 2. 딕셔너리는 어떻게 만들까?
다음은 기본 딕셔너리의 모습이다.    
`{Key1:Value1, Key2:Value2, Key3:Value3, ...}`  
Key와 Value의 쌍 여러 개가 { }로 둘러싸여 있다. 각각의 요소는 Key : Value 형태로 이루어져 있고 쉼표(,)로 구분되어 있다.  
> Key에는 변하지 않는 값을 사용하고, Value에는 변하는 값과 변하지 않는 값 모두 사용할 수 있다.  

다음 딕셔너리 예를 살펴보자.  

In [98]:
'''
Quiz1. 비어있는 딕셔너리 만들기
temp 이름의 비어있는 딕셔너리를 만들라.
'''
temp = {}

In [60]:
dic = {'name':'pey', 'phone':'0119993323', 'birth': '1118'}
dic

{'name': 'pey', 'phone': '0119993323', 'birth': '1118'}

위에서 Key는 각각 'name', 'phone', 'birth'이고, 각각의 Key에 해당하는 Value는 'pey', '0119993323', '1118'이 된다.
| key   | value       |
|-------|-------------|
| name  | pey         |
| phone | 01199993323 |
| birth | 1118        |


In [101]:
'''
Quiz2. 다음 아이스크림 이름과 희망 가격을 딕셔너리로 구성하라.
쿠키앤크림 : 1000원
민트초코 : 1200원
엄마는외계인 : 1800
'''
ice = {}
ice = {"쿠키앤크림": 1000, "민트초코": 1200, "엄마는외계인": 1800}
print(ice)

{'쿠키앤크림': 1000, '민트초코': 1200, '엄마는외계인': 1800}


### 3. 딕셔너리 쌍 추가, 삭제하기
#### 딕셔너리 쌍 추가하기

In [66]:
a = {1: 'a'}
a[2] = 'b'
a

{1: 'a', 2: 'b'}

In [67]:
a['name'] = 'pey'
a


{1: 'a', 2: 'b', 'name': 'pey'}

In [68]:
a[3] = [1,2,3]
a

{1: 'a', 2: 'b', 'name': 'pey', 3: [1, 2, 3]}

In [102]:
'''
Quiz3. 딕셔너리 쌍 추가하기
ice 딕셔너리에 아래 아이스크림 가격정보를 추가하라.
아몬드봉봉 : 3000원
초코나무숲 : 2500원
'''
ice = {"쿠키앤크림": 1000, "민트초코": 1200, "엄마는외계인": 1800}
ice["아몬드봉봉"] = 3000
ice["초코나무숲"] = 2500
print(ice)

{'쿠키앤크림': 1000, '민트초코': 1200, '엄마는외계인': 1800, '아몬드봉봉': 3000, '초코나무숲': 2500}


#### 딕셔너리 요소 삭제하기

In [69]:
del a[1]
a

{2: 'b', 'name': 'pey', 3: [1, 2, 3]}

In [117]:
'''
Quiz4. 다음 딕셔너리에서 쿠키앤크림을 삭제하라.
ice = {"쿠키앤크림": 1000, "민트초코": 1200, "엄마는외계인": 1800}
'''
ice = {"쿠키앤크림": 1000, "민트초코": 1200, "엄마는외계인": 1800}
del ice["쿠키앤크림"]
ice

{'민트초코': 1200, '엄마는외계인': 1800}

위 예제는 딕셔너리 요소를 지우는 방법을 보여 준다. `del` 함수를 사용해서 `del a[key]`처럼 입력하면 지정한 Key에 해당하는 `{key : value}` 쌍이 삭제된다.

### 딕셔너리를 사용하는 방법
"딕셔너리는 주로 어떤 것을 표현하는 데 사용할까?"라는 의문이 들 것이다. 예를 들어 4명의 사람이 있다고 가정하고, 각자의 특기를 표현할 수 있는 좋은 방법에 대해서 생각해 보자. 리스트나 문자열로는 표현하기가 상당히 까다로울 것이다. 하지만 파이썬의 딕셔너리를 사용한다면 이 상황을 표현하기가 정말 쉽다. 다음 예를 보자.

`{"김연아":"피겨스케이팅", "류현진":"야구", "박지성":"축구", "귀도":"파이썬"}`

사람 이름과 특기를 한 쌍으로 하는 딕셔너리이다. 정말 간편하지 않은가?

지금껏 우리는 딕셔너리를 만드는 방법에 대해서만 살펴보았는데 딕셔너리를 제대로 활용하기 위해서는 알아야 할 것이 더 있다. 이제부터 하나씩 알아보자.

#### 딕셔너리에서 Key 사용해 Value 얻기
다음 예를 살펴보자.


In [71]:
grade = {'pey': 10, 'julliet': 99}
grade['pey']

10

In [72]:
grade['julliet']

99

리스트나 튜플, 문자열은 요솟값을 얻고자 할 때 인덱싱이나 슬라이싱 기법 중 하나를 사용했다.   
**하지만 딕셔너리는 단 한 가지 방법뿐이다. 바로 Key를 사용해서 Value를 구하는 방법이다.**  
위 예에서 'pey'라는 Key의 Value를 얻기 위해 `grade['pey']`를 사용한 것처럼 어떤 Key의 Value를 얻기 위해서는 `딕셔너리변수이름[Key]`를 사용한다.



In [112]:
'''
Quiz5. key를 사용해 value 얻기
다음 딕셔너리를 사용하여 민트초코 가격을 출력하라.
ice = {'쿠키앤크림': 1000, '민트초코': 1200, '엄마는외계인': 1800, '아몬드봉봉': 3000, '초코나무숲': 2500}
f 포맷팅 기법을 사용하여 다음과 같이 출력하시오.
출력문 : 민트초코의 가격은 ____원입니다.
'''
ice = {'쿠키앤크림': 1000, '민트초코': 1200, '엄마는외계인': 1800, '아몬드봉봉': 3000, '초코나무숲': 2500}

print(f"민트초코의 가격은 {ice['민트초코']}원입니다.")

민트초코의 가격은 1200원입니다.


In [114]:
'''
Quiz6. key를 사용해 value값 수정하기
다음 딕셔너리에서 민트초코의 가격을 2000으로 수정하라.
ice = {'쿠키앤크림': 1000, '민트초코': 1200, '엄마는외계인': 1800, '아몬드봉봉': 3000, '초코나무숲': 2500}
'''
ice = {'쿠키앤크림': 1000, '민트초코': 1200, '엄마는외계인': 1800, '아몬드봉봉': 3000, '초코나무숲': 2500}
ice["민트초코"] = 2000
ice["민트초코"]

2000

In [73]:
a = {1:'a', 2:'b'}
a[1]

'a'

In [74]:
a[2]

'b'

먼저 `a` 변수에 `{1:'a', 2:'b'}` 딕셔너리를 대입하였다.   
위 예에서 볼 수 있듯이 `a[1]`은 'a' 값을 돌려준다. 여기에서 `a[1]`이 의미하는 것은 리스트나 튜플의 `a[1]`과는 전혀 다르다.   
딕셔너리 변수에서 [ ] 안의 숫자 1은 두 번째 요소를 뜻하는 것이 아니라 **Key에 해당하는 1을 나타낸다.**   
앞에서도 말했듯이 딕셔너리는 리스트나 튜플에 있는 인덱싱 방법을 적용할 수 없다.   
따라서 `a[1]`은 딕셔너리 `{1:'a', 2:'b'}`에서 Key가 1인 것의 Value인 'a'를 돌려주게 된다. `a[2]` 역시 마찬가지이다.

이번에는 `a`라는 변수에 앞의 예에서 사용한 딕셔너리의 Key와 Value를 뒤집어 놓은 딕셔너리를 대입해 보자

In [75]:
a = {'a':1, 'b':2}
a['a']

1

In [76]:
a['b']

2

역시 `a['a']`, `a['b']`처럼 Key를 사용해서 Value를 얻을 수 있다. 정리하면, 딕셔너리 `a`는 `a[Key]`로 입력해서 Key에 해당하는 Value를 얻는다.
  
다음 예는 이전에 한 번 언급한 딕셔너리인데 Key를 사용해서 Value를 얻는 방법을 잘 보여 준다.

In [77]:
dic = {'name':'pey', 'phone':'0119993323', 'birth': '1118'}
dic['name']

'pey'

In [80]:
dic['phone']

'0119993323'

In [79]:
dic['birth']

'1118'

### 딕셔너리 관련 함수들
딕셔너리를 자유자재로 사용하기 위해 딕셔너리가 자체적으로 가지고 있는 관련 함수를 사용해 보자.

- `keys` : Key 리스트 만들기
- `values` : Value 리스트 만들기
- `items` : Key, Value 쌍 얻기
- `clear` : Key: Value 쌍 모두 지우기
- `get` : Key로 Value 얻기
- `in` : 해당 Key가 딕셔너리 안에 있는지 조사하기

In [82]:
# Key 리스트 만들기(keys)
a = {'name': 'pey', 'phone': '0119993323', 'birth': '1118'}
a.keys()

dict_keys(['name', 'phone', 'birth'])

In [83]:
# dict_keys 객체를 리스트로 변환하기
list(a.keys())

['name', 'phone', 'birth']

In [121]:
'''
Quiz7. keys() 메서드 사용
다음의 딕셔너리로부터 key 값들로만 구성된 리스트를 생성하라.
icecream = {'쿠키앤크림': 1000, '민트초코': 1200, '엄마는외계인': 1800, '아몬드봉봉': 3000, '초코나무숲': 2500}
'''
icecream = {'쿠키앤크림': 1000, '민트초코': 1200, '엄마는외계인': 1800, '아몬드봉봉': 3000, '초코나무숲': 2500}
ice = list(icecream.keys())
print(ice)

['쿠키앤크림', '민트초코', '엄마는외계인', '아몬드봉봉', '초코나무숲']


In [84]:
# Value 리스트 만들기(values)
a.values()

dict_values(['pey', '0119993323', '1118'])

In [85]:
list(a.values())

['pey', '0119993323', '1118']

In [122]:
'''
Quiz8. values() 메서드 사용
다음의 딕셔너리로부터 value 값들로만 구성된 리스트를 생성하라.
icecream = {'쿠키앤크림': 1000, '민트초코': 1200, '엄마는외계인': 1800, '아몬드봉봉': 3000, '초코나무숲': 2500}
'''
icecream = {'쿠키앤크림': 1000, '민트초코': 1200, '엄마는외계인': 1800, '아몬드봉봉': 3000, '초코나무숲': 2500}
ice = list(icecream.values())
print(ice)

[1000, 1200, 1800, 3000, 2500]


In [86]:
# Key, Value 쌍 얻기(items)
a.items()

dict_items([('name', 'pey'), ('phone', '0119993323'), ('birth', '1118')])

In [88]:
# Key: Value 쌍 모두 지우기(clear)
a.clear()
a

{}

In [97]:
# Key로 Value얻기(get)
a = {'name':'pey', 'phone':'0119993323', 'birth': '1118'}

print(a.get('name'), a.get('phone'))

pey 0119993323


In [81]:
a = {'name':'pey', 'phone':'0119993323', 'birth': '1118'}
print('name' in a)
print('email' in a)

True
False


'name' 문자열은 a 딕셔너리의 Key 중 하나이다. 따라서 'name' in a를 호출하면 참(True)을 돌려준다.   
반대로 'email'은 a 딕셔너리 안에 존재하지 않는 Key이므로 거짓(False)을 돌려준다.